AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ReactAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-react-app"

  ReactAppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ReactAppBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub "${ReactAppBucket.Arn}/*"

Outputs:
  ReactAppBucketName:
    Description: "Name of the S3 bucket for the React app"
    Value: !Ref ReactAppBucket